name: Testing (Dev)

on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

env:
  BUILD_TYPE: Debug

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux GCC x64
            os: ubuntu-latest
            compiler_c: gcc
            compiler_cpp: g++
            coverage_c: "-O0 -g --coverage"
            coverage_cpp: "-O0 -g --coverage"

          - name: MacOS Clang x64
            os: macos-latest
            compiler_c: clang
            compiler_cpp: clang++
            coverage_c: "-O0 -g -fprofile-instr-generate -fcoverage-mapping"
            coverage_cpp: "-O0 -g -fprofile-instr-generate -fcoverage-mapping"

          - name: Windows GCC x64
            os: windows-latest
            compiler_c: gcc
            compiler_cpp: g++
            coverage_c: "-O0 -g --coverage"
            coverage_cpp: "-O0 -g --coverage"

    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.27"  # use most recent 3.27.x version
          ninjaVersion: "^1"     # use most recent 1.x version

      - name: CMake Setup
        run: cmake -S . -B ${{github.workspace}}/build -G Ninja -D \
          CMAKE_C_COMPILER=${{matrix.compiler_c}} \
          CMAKE_CXX_COMPILER=${{matrix.compiler_cpp}} \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_C_FLAGS=${{env.COVERAGE_C}} \
          -DCMAKE_CXX_FLAGS=${{env.COVERAGE_C}}

      - name: CMake Build
        run: cmake --build ${{github.workspace}}/build \
          --config ${{env.BUILD_TYPE}} \
          --target test_caravan

      - name: Run Tests
        working-directory: ./build/test
        run: ctest --output-on-failure
