name: Tests

on:
  push:
    branches: [ tui ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux GCC
            os: ubuntu-latest
            compiler_cc: gcc
            compiler_cpp: g++

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.27.0"  # use most recent 3.27.x version
          ninjaVersion: "^1.0"     # use most recent 1.x version

      - name: CMake Setup
        run: cmake -S . -B ${{github.workspace}}/build -G Ninja -D CMAKE_C_COMPILER=${{matrix.compiler_cc}} CMAKE_CXX_COMPILER=${{matrix.compiler_cpp}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target tests

      - name: ls build
        run: ls ${{github.workspace}}/build

      - name: ls build/Release
        run: ls ${{github.workspace}}/build/Release

      - name: Run Tests
        run: ./${{github.workspace}}/build/${{env.BUILD_TYPE}}/tests
