name: Tests

on:
  push:
    branches: [ ai ]

env:
  BUILD_TYPE: Debug

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux GCC x64
            os: ubuntu-latest
            compiler_cc: gcc
            compiler_cpp: g++

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.27.0"  # use latest 3.27.x version
          ninjaVersion: "^1.0"     # use latest 1.x version

      - name: CMake Setup
        run: cmake -S . -B ${{github.workspace}}/build -G Ninja -D CMAKE_C_COMPILER=${{matrix.compiler_cc}} CMAKE_CXX_COMPILER=${{matrix.compiler_cpp}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target tests

      - name: Run Tests
        working-directory: ./build
        run: ctest --output-on-failure
