name: Windows

on:
  release:
    types: [ created ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Windows GCC
            os: windows-latest
            compiler_cc: gcc
            compiler_cpp: g++

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.27.0"  # use most recent 3.27.x version
          ninjaVersion: "^1.0"     # use most recent 1.x version

      - name: CMake Setup
        run: cmake -S . -B ${{github.workspace}}/build -G Ninja -D CMAKE_C_COMPILER=${{matrix.compiler_cc}} CMAKE_CXX_COMPILER=${{matrix.compiler_cpp}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target caravan

      - name: Rename Executable
        working-directory: ./build
        run: mv caravan.exe caravan_windows_x64.exe

      - name: Upload Executable to Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./build/caravan_windows_x64.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
