name: Windows

on:
  push:
    branches: [ develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: lukka/get-cmake@v3.25.2
        with:
          cmakeVersion: 3.25.2
          ninjaVersion: 1.11.1

      - name: Check Dependencies
        run: |
          cmake --version
          ninja --version

      - name: CMake Setup
        run: cmake -S . -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      #- name: Build (caravan)
      #  run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target caravan

      - name: Build (tests)
        run: cmake --build ${{github.workspace}}/build --target test_caravan

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest
